name: score_pubspec
description: A sample command-line to score pubspec.lock
version: 0.0.3
homepage: https://github.com/agacemi/score_pubspec.git
repository: https://github.com/agacemi/score_pubspec.git
environment:
  sdk: ">=3.0.0 <4.0.0"
executables:
  score_pubspec:

# dependencies:
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.4.0
  build_runner: ^2.4.6
  github: ^9.18.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  pub_api_client: ^2.6.0
  pubspec_lock_parse: ^2.2.0
