name: score_pubspec
description: A sample command-line to score pubspec.lock
version: 0.0.5
homepage: https://github.com/agacemi/score_pubspec.git
repository: https://github.com/agacemi/score_pubspec.git
environment:
  sdk: ">=3.0.0 <4.0.0"
executables:
  score_pubspec:

# dependencies:
dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
  build_runner: ^2.4.9
dependencies:
  args: ^2.7.0
  github: ^9.25.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  pub_api_client: ^2.7.0
  pubspec_lock_parse: ^2.2.0
